# method
GET
# url
https://api.1inch.exchange/v3.0/137/swap

# query params
&fromTokenAddress = 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
&toTokenAddress = 0x8f3cf7ad23cd3cadbd9735aff958023239c6a063
&amount = 100000000000000000000000000
&fromAddress = 0x8cf1839B4e5eE89a31d3390eF5a0927918A5Da9A
&slippage = 10

# headers
@Accept: application/json


%%%

# Duration: 5711 ms
# URL: https://api.1inch.exchange/v3.0/137/swap?&fromTokenAddress=0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270&toTokenAddress=0x8f3cf7ad23cd3cadbd9735aff958023239c6a063&amount=100000000000000000000000000&fromAddress=0x8cf1839B4e5eE89a31d3390eF5a0927918A5Da9A&slippage=10

# HTTP/1.1 500 Internal Server Error

@Date: Sun, 29 Aug 2021 20:36:55 GMT
@Content-Type: application/json; charset=utf-8
@Content-Length: 190
@Connection: keep-alive
@Access-Control-Allow-Origin: *
@Cache-Control: public, max-age=3, s-maxage=3
@Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
@Etag: W/"be-4roi8Wuwl+7K2kphmHsOMUVHXHk"
@Expect-Ct: max-age=0
@Referrer-Policy: no-referrer
@Strict-Transport-Security: max-age=15552000; includeSubDomains
@Vary: Origin, Accept-Encoding
@X-Content-Type-Options: nosniff
@X-Dns-Prefetch-Control: off
@X-Download-Options: noopen
@X-Frame-Options: SAMEORIGIN
@X-Permitted-Cross-Domain-Policies: none
@X-Xss-Protection: 0
@CF-Cache-Status: MISS
@Server: cloudflare
@CF-RAY: 686892e65cc10017-WAW
@alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400

{
  "statusCode": 500,
  "message": "Not enough 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270 balance. Amount: 100000000000000000000000000. Balance: 299999999999000000",
  "error": "Internal Server Error"
}